# Vanity Num Generator Cloud Formation Template
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Vanity Number Generator

Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    # The PermissionsBoundary allows users to safely develop with their function's permissions constrained
    # to their current application. All the functions and roles in this application have to include it and
    # it has to be manually updated when you add resources to your application.
    # More information in https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html
    PermissionsBoundary: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/${AppId}-${AWS::Region}-PermissionsBoundary'

Parameters:
  AppId:
    Type: String
  TableName:
    Type: String
    Default: vanity_numbers_prod
  ApiGatewayName:
    Type: String
    Default: vanity_api_gateway
  ApiGatewayHttpMethod:
    Type: String
    Default: GET
  SamBucketPolicyARN:
    Type: String
    Default: arn:aws:iam::345859732721:policy/SamBucketAccess
  
Resources:
  MyApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: Vanity Number Api Gateway
      StageName: Staging

  vanityNumbersDbTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: customerPhone
          AttributeType: S
        - AttributeName: lastUpdated
          AttributeType: S
      KeySchema: 
        - AttributeName: customerPhone
          KeyType: HASH
        - AttributeName: lastUpdated
          KeyType: RANGE
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: !Ref TableName
      Tags: 
        - Key: Creator
          Value: Michael
        - Key: Table Name
          Value: Vanity Numbers

  vanityNumberGeneratorLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: src/handlers/generate-vanity-number.generateNumberHandler
      Runtime: nodejs14.x
      CodeUri: .
      Description: Take a phone number and generate 3 vanity numbers, and then select the best one.
      MemorySize: 128
      Timeout: 3
      Policies:
        - AWSLambdaBasicExecutionRole
        - !Ref SamBucketPolicyARN

  insertGeneratedNumbersLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler:  src/handlers/insert-vanity-number.insertNumberHandler
      Runtime: nodejs14.x
      CodeUri: .
      Description: Insert the vanity number options and other info to the caller's corresponding DynamoDB record.
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
      MemorySize: 128
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
        - !Ref SamBucketPolicyARN

  getCustomerDataLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler:  src/handlers/check-customer-data.getCustomerDataHandler
      Runtime: nodejs14.x
      CodeUri: .
      Description: Return the data from the dynamoDB lookukp for the caller's phone number.
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
      MemorySize: 128
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
        - !Ref SamBucketPolicyARN

  getCallHistoryLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler:  src/handlers/get-call-history.getCallHistoryHandler
      Runtime: nodejs14.x
      CodeUri: .
      Description: Return the 5 most recent records in the dynamoDB table.
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
      Events:
        VanityNumberApi:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /call-history
            Method: GET
      MemorySize: 128
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
        - !Ref SamBucketPolicyARN